services:
# WatchTower
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    environment:
      - WATCHTOWER_SCOPE=main-images
    networks:
      - traefik-server
# Traefik
  traefik:
    image: ghcr.io/benja-m24/traefik-servermanager:lts
    ports:
      - 80:80 # HTTP port
      - 443:443 # HTTPS port
    restart: always
    labels:
      # WatchTower monitoring
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=main-images

      # Traefik configuration
      - traefik.enable=true
      - traefik.docker.network=traefik-server
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080

      # HTTP router configuration
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.${DOMAIN?Variable not set}`)

      # HTTPS router configuration
      - traefik.http.routers.traefik-dashboard-https.entrypoints=https
      - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-dashboard-https.tls=true
      - traefik.http.routers.traefik-dashboard-https.tls.certresolver=le
      - traefik.http.routers.traefik-dashboard-https.service=api@internal

      # HTTPS redirect middleware
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect

      # HTTP Basic Auth middleware
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
      - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket for reading service labels
      - traefik-server-certificates:/certificates # Certificate storage
    command:
      # Docker provider configuration
      - --providers.docker
      - --providers.docker.exposedbydefault=false

      # Entrypoints configuration
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      # Let's Encrypt configuration
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true

      # Logging and API configuration
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-server # Public network for Traefik and other services

volumes:
  traefik-server-certificates: # Persistent volume for certificates

networks:
  traefik-server:
    external: true # Use pre-existing traefik-server network